# Producto interno entra una matriz y un vector

In [14]:
import numpy as np

In [15]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [16]:
matriz * vector

array([[ 2,  6],
       [ 6, 12],
       [10, 18]])

In [17]:
matriz.dot(vector)

array([ 8, 18, 28])

No es lo mismo multiplicar una matriz por un vector que hacer el producto interno. En la primera se está aplicando broadcasting.

In [18]:
vector*matriz

array([[ 2,  6],
       [ 6, 12],
       [10, 18]])

**matriz * vector** es igual que  **vector*matriz**

Dos formas de aplicar el producto interno

In [19]:
B = matriz.dot(vector)
C = np.dot(matriz, vector)
D = matriz@vector
print(B)
print(C)
print(D)

[ 8 18 28]
[ 8 18 28]
[ 8 18 28]
