# Matriz Ortogonal

Una matriz ortogonal es una matriz cuadrada cuya matriz inversa coincide con su matriz traspuesta.

Es la matriz cuyos vectores filas son ortonormales mutuamente (lo mismo con los vectores columnas)

NO existe la definición de *matriz ortonormal*.

In [1]:
import numpy as np

In [2]:
matriz = np.array([[1,0,0],
                   [0,1,0],
                   [0,0,1]
                  ])
print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Comprobando que las columnas son ortogonales

In [3]:
print(matriz[:,0].dot(matriz[:,1]))

0


In [4]:
print(matriz[:,0].dot(matriz[:,2]))

0


In [5]:
print(matriz[:,1].dot(matriz[:,2]))

0


comprobando que las columnas tienen norma 1

In [6]:
print(np.linalg.norm(matriz[:,0]))
print(np.linalg.norm(matriz[:,1]))
print(np.linalg.norm(matriz[:,2]))

1.0
1.0
1.0


Comprobando que las filas tambien son ortogonales

In [7]:
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[2,:]))
print(matriz[1,:].dot(matriz[2,:]))

0
0
0


comprobando que las filas tambien tienen norma 1

In [8]:
print(np.linalg.norm(matriz[0,:]))
print(np.linalg.norm(matriz[1,:]))
print(np.linalg.norm(matriz[2,:]))

1.0
1.0
1.0


$$ A^T = A^{-1} $$

$$ A^T \cdot A = A \cdot A^T = I $$

Manera sencilla de generar matrices ortogonales

In [9]:
A = np.array([[np.cos(100), -np.sin(100)],
             [np.sin(100), np.cos(100)]])
print(A)

[[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


norma

In [10]:
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


ángulo

In [11]:
print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))

0.0
0.0


A por A^T nos da la identidad pero aquí se ven los efectos de no activar

`
np.set_printoptions(suppress=True)
`

In [12]:
A_t = A.T
print(A_t.dot(A))
print(A.dot(A_t))

[[ 1.00000000e+00 -7.93771519e-18]
 [-7.93771519e-18  1.00000000e+00]]
[[1.00000000e+00 7.93771519e-18]
 [7.93771519e-18 1.00000000e+00]]


In [13]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [14]:
print(A_t)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


lo que debió haber sido un error por no poder dividir entre cero, me da un número extremadamente grande

In [15]:
print(1/A_t.dot(A))

[[ 1.00000000e+00 -1.25980837e+17]
 [-1.25980837e+17  1.00000000e+00]]
