# Transposición

In [62]:
import numpy as np

In [63]:
escalar = 2
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,31],[7,8,9,32]],
    [[11,12,13,33],[14,15,16,34],[17,18,19,35]]
])

In [64]:
vector_t = vector.T
print(vector_t)

[3 4 5 6]


In [65]:
matriz_t = matriz.T
print(matriz_t)
print(matriz.shape)
print(matriz_t.shape)

[[1 3 5]
 [2 4 6]]
(3, 2)
(2, 3)


In [66]:
tensor_t = tensor.T
print(tensor_t)

[[[ 1 11]
  [ 4 14]
  [ 7 17]]

 [[ 2 12]
  [ 5 15]
  [ 8 18]]

 [[ 3 13]
  [ 6 16]
  [ 9 19]]

 [[30 33]
  [31 34]
  [32 35]]]


In [67]:
print(tensor)

[[[ 1  2  3 30]
  [ 4  5  6 31]
  [ 7  8  9 32]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]]


In [68]:
print(tensor.shape)
print(tensor_t.shape)

(2, 3, 4)
(4, 3, 2)


## Transposición de una transposición

In [69]:
matriz_t_t = matriz_t.T
print(matriz_t_t)

[[1 2]
 [3 4]
 [5 6]]


In [70]:
print(matriz)

[[1 2]
 [3 4]
 [5 6]]


# Suma de matrices

deben ser del mismo tamaño

In [71]:
A = matriz
B = matriz_t

In [72]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
C = A+B
print(A)
print(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[6 5]
 [4 3]
 [2 1]]
[[7 7]
 [7 7]
 [7 7]]


In [73]:
D = A + escalar
print(D)

[[3 4]
 [5 6]
 [7 8]]
