# Broadcasting

## entre vectores y matrices

In [8]:
import numpy as np

In [9]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [10]:
# A = vector + matriz
# ERROR

In [11]:
matriz.T + vector

array([[ 4,  7, 10],
       [ 5,  8, 11]])

In [13]:
# matriz + vector.T
# ERROR

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

## entre matrices y escalares

In [6]:
C = matriz + 42

In [7]:
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [8]:
D = matriz + np.array([[42],[42],[42]])
print(D)

[[43 44]
 [45 46]
 [47 48]]
