# Propiedades producto interno

In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

## Propiedad asociativa

In [3]:
A.dot(B.dot(C))

array([[ 60,  26],
       [145,  63],
       [295, 129]])

In [4]:
A.dot(B).dot(C)

array([[ 60,  26],
       [145,  63],
       [295, 129]])

## Propiedad distributiva

In [5]:
A.dot(B+C)

array([[ 26,  17],
       [ 62,  41],
       [122,  83]])

In [6]:
(A.dot(B))+(A.dot(C))

array([[ 26,  17],
       [ 62,  41],
       [122,  83]])

## Propiedad conmutativa

El productor interno de matrices NO cumple la *propiedad conmutativa*

In [7]:
B.dot(C)

array([[15,  7],
       [10,  4]])

In [8]:
C.dot(B)

array([[ 5, 10],
       [ 8, 14]])

Pero, la multiplicación de vectores sí es conmutativa

In [9]:
v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]])

In [10]:
v1.T.dot(v2)

array([[41]])

In [11]:
v2.T.dot(v1)

array([[41]])